<p> <span class="color-yellow">Tras dos semanas, </span>en cita control, Iván reporta:</p>
<ul>
    <li>Una marcada respuesta al dolor (0/10) y distensión abdomina.<span class="numeros-arriba">8-10</span></li>
    <li>Modulación importante en la consistencia de las heces.<span class="numeros-arriba">8-10</span></li>
</ul>




<p><span class="color-yellow">Hay mejoría, </span>pero no es completa.</p>




<p>Aunque esta podría ser una alternativa de tratamiento, existe una opción más adecuada que brinda mayores beneficios.</p>
